### ISSUE TITLE
Convert non-epsg:4326 CRS package-wide

### ISSUE THREAD

**Issue by sckott** [ropensci/geojsonio#101]
with parameter to toggle on or off

**Comment by ateucher** [comment]
Parameter name `convert_wgs84`? or just `WGS84`? 

I think, at least for this version, the default value should be `FALSE` (i.e., don't convert) otherwise it will cause unexpected results in existing code. If `FALSE` we could throw a warning or a message that WGS84 is the standard and converting to it will/may be the default behaviour in a future version?

For sf and Spatial objects that don't have a CRS, and/or for other classes, should we throw a warning or a message that it was unable to detect a CRS and hence no conversion occured?

I think I have most of the [code for the sf classes](https://github.com/ropensci/geojsonio/blob/master/R/geojson_list.R#L395-L405), it's just commented out right now.

The code for Spatial classes will be very similar, just using `rgdal::spTransform(x, CRS("+init=epsg:4326"))` in place of `sf::st_transform(x, 4326)`

**Comment by sckott** [comment]
* probably `convert_wgs84 `
* I agree default to `FALSE`

> If `FALSE` we could throw a warning or a message that WGS84 is the standard and converting to it will/may be the default behaviour in a future version?

that sounds good to me. 

> For sf and Spatial objects that don't have a CRS, and/or for other classes, should we throw a warning or a message that it was unable to detect a CRS and hence no conversion occured?

hmm, possibly allow a user to pass in the CRS if they know it (but it's for some reason not attached to the data)?   or is that a bad idea?

**Comment by ateucher** [comment]
> hmm, possibly allow a user to pass in the CRS if they know it (but it's for some reason not attached to the data)? or is that a bad idea?

That could work for sp and sf classes, for sure. Should probably do some minimal checking to make sure a CRS passed in is valid, but beyond that, *caveat emptor* I would say.

**Comment by sckott** [comment]
Okay, but for numeric/data.frame/etc. classes - always just assume WGS84?

**Comment by ateucher** [comment]
I think that's the only way to do it... the other option is, if they pass in a CRS, convert the object to sf or sp, transform it to WGS84, then convert to geojson. But that would probably require (for example): **numeric -> geojson -> Spatial* -> spTransform -> geojson**. Which seems crazy

**Comment by sckott** [comment]
yeah, let's just assume WGS84

**Comment by ateucher** [comment]
Started crs-convert branch. I think the functionality is there, just need to add the parameter to generics and methods and tuck `detect_convert_crs` into the right places

Need it in:
- `geojson_json`, 
- `geojson_list',
- `geojson_write`

Anything else?

**Comment by sckott** [comment]
Add new tests for functions that get this functionality

**Comment by ateucher** [comment]
Closed by #102
