### ISSUE TITLE
rgeos not all gone yet

### ISSUE THREAD

**Issue by rsbivand** [ropensci/geojsonio#207]
Following 0.11.1 and 0.11.2, I'm afraid that I still see references to the `"SpatialRing"` etc., classes which are defined in `rgeos` not `sp`, so #185 probably isn't done yet: https://github.com/search?q=repo%3Aropensci%2Fgeojsonio%20SpatialRing&type=code. The CMD check 00install.out log is:

[00install.out.log](https://github.com/ropensci/geojsonio/files/12521985/00install.out.log)

**Comment by mikemahoney218** [comment]
Thanks @rsbivand -- as always, I highly appreciate the amount of work & care you're doing to retire these packages.

I _believe_ the bits in the install log come from here, where these functions are made defunct:
https://github.com/ropensci/geojsonio/blob/6202af081025015872345d5a9b8c17caaec54d18/R/deprecated.R#L77-L106

Do you know if those install messages will cause issues with CRAN? I can drop those defunct functions entirely if so; otherwise, it might be nice to leave the deprecation messages in place.

That said, there's a few spots in the code search that definitely should be removed, thank you for flagging!

**Comment by rsbivand** [comment]
Thanks. `"SpatialCollections"` are from `rgeos` too, though:

```
> getClass("Spatial")
Class "Spatial" [package "sp"]

Slots:
                              
Name:         bbox proj4string
Class:      matrix         CRS

Known Subclasses: 
Class "SpatialPoints", directly
Class "SpatialMultiPoints", directly
Class "SpatialGrid", directly
Class "SpatialLines", directly
Class "SpatialPolygons", directly
Class "SpatialPointsDataFrame", by class "SpatialPoints", distance 2
Class "SpatialPixels", by class "SpatialPoints", distance 2
Class "SpatialMultiPointsDataFrame", by class "SpatialMultiPoints", distance 2
Class "SpatialGridDataFrame", by class "SpatialGrid", distance 2
Class "SpatialLinesDataFrame", by class "SpatialLines", distance 2
Class "SpatialPixelsDataFrame", by class "SpatialPoints", distance 3
Class "SpatialPolygonsDataFrame", by class "SpatialPolygons", distance 2
> library(rgeos)
> getClass("SpatialCollections")
Class "SpatialCollections" [package "rgeos"]

Slots:
                                                                  
Name:             pointobj             lineobj             ringobj
Class:   SpatialPointsNULL    SpatialLinesNULL    SpatialRingsNULL
                                                                  
Name:              polyobj           plotOrder                bbox
Class: SpatialPolygonsNULL             integer              matrix
                          
Name:          proj4string
Class:                 CRS

Extends: "Spatial"
```

**Comment by mikemahoney218** [comment]
Thanks again -- went through and removed the SpatialRing and SpatialCollections references throughout the package and cut a new release, so the CRAN version should be rgeos-free.
