### ISSUE TITLE
geojson_read - Cannot open data source

### ISSUE THREAD

**Issue by jeancabouat** [ropensci/geojsonio#98]
Hi,
I have the following error and can't find why, any ideas ?
Thks
Jean

```r
out <- geojson_read("new-york_new-york_osm_point.shp", method = "local", parse = TRUE)
Error in rgdal::ogrListLayers(input) : Cannot open data source
```

**Comment by sckott** [comment]
Can you share the file? I can't reproduce the problem without the file, or if it's too big or private, share another that gives the same problem for you.

**Comment by jeancabouat** [comment]
The file is available on:

https://s3.amazonaws.com/metro-extracts.mapzen.com/new-york_new-york.osm2pgsql-geojson.zip

Thks !

**Comment by jeancabouat** [comment]
Available on : https://s3.amazonaws.com/metro-extracts.mapzen.com/new-york_new-york.osm2pgsql-shapefiles.zip

**Comment by jeancabouat** [comment]
From there: https://mapzen.com/data/metro-extracts/metro/new-york_new-york/

**Comment by sckott** [comment]
worked for me. 

* Downloaded https://s3.amazonaws.com/metro-extracts.mapzen.com/new-york_new-york.osm2pgsql-shapefiles.zip
* Unzipped it, can do manually in file finder/etc. or programatically in R via `unzip()`
* Then inside the directory of the unzipped folder, ran `out <- geojson_read("new-york_new-york_osm_point.shp", method = "local", parse = TRUE)` it took a long time, but reasonable because the .dbf file associated is 360 mb, .shp file is only about 6 mb though

maybe you weren't inside the folder where the .shp file was?

**Comment by sckott** [comment]
@jeancabouat did you get a chance to try this again?

**Comment by jeancabouat** [comment]
Many thanks for your help Sckott.
Actually, I didn't have all the needed files.
It perfectly works now !

**Comment by sckott** [comment]
great, good
